# Generated by Django 5.2.6 on 2025-09-24 21:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'ItemUnits',
                'db_table': 'item_units',
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='TotalBalance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latest_withdrawal_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_withdrawer', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'total_balance',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField()),
                ('first_name', models.CharField(default="Didn't provide")),
                ('last_name', models.CharField(default="Didn't provide")),
                ('email', models.CharField(default="Didn't provide")),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(db_column='unit_id', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage_app.itemunits')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='StoreItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage_app.items')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage_app.stores')),
            ],
            options={
                'verbose_name_plural': 'Store_Items',
                'db_table': 'store_items',
            },
        ),
        migrations.CreateModel(
            name='ProductsExchanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store_items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage_app.storeitems')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage_app.transactions')),
            ],
            options={
                'verbose_name': 'Product Exchanged',
                'verbose_name_plural': 'Prodcuts Exchanged',
                'db_table': 'products_exchanged',
            },
        ),
        migrations.AddField(
            model_name='transactions',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='mainpage_app.users'),
        ),
    ]
