# Use an official PostgreSQL image as a parent image
FROM postgres:alpine

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_DB=fintechapp

# Expose the PostgreSQL port
EXPOSE 5432